# Generated by Django 3.0.8 on 2020-07-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbmodel',
            old_name='name',
            new_name='saved_dict',
        ),
        migrations.RemoveField(
            model_name='dbmodel',
            name='value',
        ),
    ]
